# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: shoot-rsyslog-relp
  namespace: shoot--foo--bar
spec:
  type: shoot-rsyslog-relp