apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: rsyslog-relp-echo-server
build:
  insecureRegistries:
    - registry.local.gardener.cloud:5000
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rsyslog-relp-echo-server
      docker:
        cacheFrom:
          - local-skaffold/gardener-extension-shoot-rsyslog-relp-echo-server
  local: {}
deploy:
  helm:
    releases:
      - name: rsyslog-relp-echo-server
        namespace: rsyslog-relp-echo-server
        createNamespace: true
        wait: true
        chartPath: example/local/charts/rsyslog-relp-echo-server
        setValueTemplates:
          images.rsyslog: '{{.IMAGE_FULLY_QUALIFIED_local_skaffold_gardener_extension_shoot_rsyslog_relp_echo_server}}'
        setValues:
          service.clusterIP: 10.2.64.54
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: extension
build:
  insecureRegistries:
    - registry.local.gardener.cloud:5000
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rsyslog-relp
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-shoot-rsyslog-relp
            - cmd/gardener-extension-shoot-rsyslog-relp/app
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/apis/rsyslog
            - pkg/apis/rsyslog/install
            - pkg/apis/rsyslog/v1alpha1
            - pkg/cmd/rsyslogrelp
            - pkg/component/rsyslogrelpconfigcleaner
            - pkg/constants
            - pkg/controller/lifecycle
            - imagevector
            - imagevector/images.yaml
            - pkg/utils
            - pkg/webhook/operatingsystemconfig
            - pkg/webhook/operatingsystemconfig/resources/auditrules/00-base-config.rules
            - pkg/webhook/operatingsystemconfig/resources/auditrules/10-privilege-escalation.rules
            - pkg/webhook/operatingsystemconfig/resources/auditrules/11-privileged-special.rules
            - pkg/webhook/operatingsystemconfig/resources/auditrules/12-system-integrity.rules
            - pkg/webhook/operatingsystemconfig/resources/templates/60-audit.conf.tpl
            - pkg/webhook/operatingsystemconfig/resources/templates/scripts/configure-rsyslog.tpl.sh
            - pkg/webhook/operatingsystemconfig/resources/templates/scripts/process-rsyslog-pstats.tpl.sh
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-shoot-rsyslog-relp
manifests:
  kustomize:
    paths:
    - local-setup
deploy:
  # --server-side apply is a workaround for https://github.com/gardener/gardener/issues/10267.
  # kubectl apply attempts a strategic merge patch which fails for a ControllerDeployment.
  # For more details, see https://github.com/gardener/gardener/issues/10267.
  #
  # TODO: Switch back to "kubectl: {}" when the above issue is resolved.
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
resourceSelector:
  # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
  allow:
  - groupKind: ControllerDeployment.core.gardener.cloud
    image:
    - .helm.values.image.ref
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: admission
build:
  insecureRegistries:
    - registry.local.gardener.cloud:5000
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rsyslog-relp-admission
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-shoot-rsyslog-relp-admission
            - cmd/gardener-extension-shoot-rsyslog-relp-admission/app
            - pkg/admission/cmd
            - pkg/admission/validator
            - pkg/apis/rsyslog
            - pkg/apis/rsyslog/install
            - pkg/apis/rsyslog/v1alpha1
            - pkg/apis/rsyslog/validation
            - pkg/constants
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-shoot-rsyslog-relp-admission
deploy:
  helm:
    releases:
      - name: shoot-rsyslog-relp-admission-application
        namespace: garden
        wait: true
        chartPath: charts/gardener-extension-shoot-rsyslog-relp-admission/charts/application
        setValueTemplates:
          gardener.virtualCluster.enabled: false
      - name: shoot-rsyslog-relp-admission-runtime
        namespace: garden
        wait: true
        chartPath: charts/gardener-extension-shoot-rsyslog-relp-admission/charts/runtime
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_gardener_extension_shoot_rsyslog_relp_admission}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_gardener_extension_shoot_rsyslog_relp_admission}}@{{.IMAGE_DIGEST_local_skaffold_gardener_extension_shoot_rsyslog_relp_admission}}'
          gardener.virtualCluster.enabled: false
profiles:
  - name: remote-extension
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValues
        value:
          vpa.enabled: false
