apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: rsyslog-relp-echo-server
build:
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rsyslog-relp-echo-server
      docker:
        cacheFrom:
          - local-skaffold/gardener-extension-shoot-rsyslog-relp-echo-server
  local: {}
deploy:
  helm:
    releases:
      - name: rsyslog-relp-echo-server
        namespace: rsyslog-relp-echo-server
        createNamespace: true
        wait: true
        chartPath: example/local/charts/rsyslog-relp-echo-server
        setValueTemplates:
          images.rsyslog: '{{.IMAGE_FULLY_QUALIFIED_local_skaffold_gardener_extension_shoot_rsyslog_relp_echo_server}}'
        setValues:
          service.clusterIP: 10.2.64.54
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: extension
build:
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rsyslog-relp
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-shoot-rsyslog-relp
            - cmd/gardener-extension-shoot-rsyslog-relp/app
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/apis/rsyslog
            - pkg/apis/rsyslog/install
            - pkg/apis/rsyslog/v1alpha1
            - pkg/cmd/rsyslogrelp
            - pkg/component/rsyslogrelpconfigcleaner
            - pkg/constants
            - pkg/controller/config
            - pkg/controller/lifecycle
            - imagevector
            - imagevector/images.yaml
            - pkg/utils
            - pkg/webhook/operatingsystemconfig
            - pkg/webhook/operatingsystemconfig/resources/auditrules/00-base-config.rules
            - pkg/webhook/operatingsystemconfig/resources/auditrules/10-privilege-escalation.rules
            - pkg/webhook/operatingsystemconfig/resources/auditrules/11-privileged-special.rules
            - pkg/webhook/operatingsystemconfig/resources/auditrules/12-system-integrity.rules
            - pkg/webhook/operatingsystemconfig/resources/templates/60-audit.conf.tpl
            - pkg/webhook/operatingsystemconfig/resources/templates/scripts/configure-rsyslog.tpl.sh
            - pkg/webhook/operatingsystemconfig/resources/templates/scripts/process-rsyslog-pstats.tpl.sh
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-shoot-rsyslog-relp
resourceSelector:
  allow:
    # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
    - groupKind: ControllerDeployment.core.gardener.cloud
      image: [".*"]
manifests:
  kustomize:
    paths:
    - local-setup
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: admission
build:
  artifacts:
    - image: local-skaffold/gardener-extension-shoot-rsyslog-relp-admission
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-shoot-rsyslog-relp-admission
            - cmd/gardener-extension-shoot-rsyslog-relp-admission/app
            - pkg/admission/cmd
            - pkg/admission/validator
            - pkg/apis/rsyslog
            - pkg/apis/rsyslog/install
            - pkg/apis/rsyslog/v1alpha1
            - pkg/apis/rsyslog/validation
            - pkg/constants
            - pkg/utils
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-shoot-rsyslog-relp-admission
deploy:
  helm:
    releases:
      - name: shoot-rsyslog-relp-admission
        namespace: garden
        wait: true
        chartPath: charts/gardener-extension-shoot-rsyslog-relp-admission
        setValueTemplates:
          global.image.repository: '{{.IMAGE_REPO_local_skaffold_gardener_extension_shoot_rsyslog_relp_admission}}'
          global.image.tag: '{{.IMAGE_TAG_local_skaffold_gardener_extension_shoot_rsyslog_relp_admission}}@{{.IMAGE_DIGEST_local_skaffold_gardener_extension_shoot_rsyslog_relp_admission}}'
profiles:
  - name: remote-extension
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues
        value:
          global.vpa.enabled: false
