apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: rsyslog-relp-echo-server
build:
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/rsyslog-relp-echo-server
    docker:
      cacheFrom:
      - eu.gcr.io/gardener-project/gardener/extensions/rsyslog-relp-echo-server
  local: {}
deploy:
  helm:
    releases:
    - name: rsyslog-relp-echo-server
      namespace: rsyslog-relp-echo-server
      createNamespace: true
      wait: true
      chartPath: example/local/charts/rsyslog-relp-echo-server
      setValueTemplates:
        images.rsyslog: '{{.IMAGE_FULLY_QUALIFIED_eu_gcr_io_gardener_project_gardener_extensions_rsyslog_relp_echo_server}}'
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: extension
build:
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/shoot-rsyslog-relp
    ko:
      dependencies:
        paths:
        - charts
        - cmd/gardener-extension-shoot-rsyslog-relp/app
        - pkg/apis/config
        - pkg/apis/config/v1alpha1
        - pkg/apis/rsyslog
        - pkg/apis/rsyslog/install
        - pkg/apis/rsyslog/v1alpha1
        - pkg/cmd/rsyslogrelp
        - pkg/constants
        - pkg/controller/config
        - pkg/controller/lifecycle
        - pkg/imagevector
        - pkg/utils
        - vendor
        - VERSION
      main: ./cmd/gardener-extension-shoot-rsyslog-relp
resourceSelector:
  allow:
  # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
  - groupKind: ControllerDeployment.core.gardener.cloud
    image: [".*"]
manifests:
  rawYaml:
    - example/controller-registration.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: admission
build:
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/shoot-rsyslog-relp-admission
    ko:
      dependencies:
        paths:
        - cmd/gardener-extension-shoot-rsyslog-relp-admission/app
        - pkg/admission/cmd
        - pkg/admission/validator
        - pkg/apis/rsyslog
        - pkg/apis/rsyslog/install
        - pkg/apis/rsyslog/v1alpha1
        - pkg/apis/rsyslog/validation
        - pkg/constants
        - pkg/utils
        - vendor
        - VERSION
      main: ./cmd/gardener-extension-shoot-rsyslog-relp-admission
deploy:
  helm:
    hooks:
      before:
      - host:
          command:
          - kubectl
          - apply
          - -f
          - example/local/admission/networkpolicy.yaml
    releases:
    - name: shoot-rsyslog-relp-admission
      namespace: garden
      wait: true
      chartPath: charts/gardener-extension-shoot-rsyslog-relp-admission
      valuesFiles:
        - "example/local/admission/values.yaml"
      setValueTemplates:
        global.image.repository: '{{.IMAGE_REPO_eu_gcr_io_gardener_project_gardener_extensions_shoot_rsyslog_relp_admission}}'
        global.image.tag: '{{.IMAGE_TAG_eu_gcr_io_gardener_project_gardener_extensions_shoot_rsyslog_relp_admission}}@{{.IMAGE_DIGEST_eu_gcr_io_gardener_project_gardener_extensions_shoot_rsyslog_relp_admission}}'
