# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels" . | indent 8 }}
    spec:
      containers:
      - name: pause-container
        image: {{ .Values.images.pause }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
      initContainers:
      - name: rsyslog-configuration-cleaner
        image: {{ .Values.images.alpine }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        securityContext:
          privileged: true
        command:
        - "sh"
        - "-c"
        - |
          if [[ -d /host/etc/audit/rules.d.old ]]; then
            rm -rf /host/etc/audit/rules.d
            mv /host/etc/audit/rules.d.old /host/etc/audit/rules.d
          fi
          if [[ -f /host/etc/audit/plugins.d/syslog.conf ]]; then
            sed -i 's/yes/no/g' /host/etc/audit/plugins.d/syslog.conf
          fi

          if [[ -d /host/etc/rsyslog.d.old ]]; then
            rm -rf /host/etc/rsyslog.d
            mv /host/etc/rsyslog.d.old /host/etc/rsyslog.d
          fi
          if [[ -d /host/{{ .Values.certificatePath }} ]]; then
            rm -rf /host/{{ .Values.certificatePath }}
          fi

          chroot /host /bin/bash -c 'augenrules --load && systemctl restart auditd && systemctl restart rsyslog'
        volumeMounts:
        - name: host-root-volume
          mountPath: /host
          readOnly: false
          mountPropagation: HostToContainer
      hostPID: true
      volumes:
      - name: host-root-volume
        hostPath:
          path: /