# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0


apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-relp-echo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rsyslog-relp-echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  60-relp.conf: |
    module(
      load="imrelp"
      tls.tlslib="openssl"
    )

    input(
      type="imrelp"
      port="10250"
      maxDataSize="10k"
      tls="off"
    )

    input(
      type="imrelp"
      port="10350"
      maxDataSize="10k"
      tls="on"
      tls.caCert="/var/lib/rsyslog-relp/tls/ca"
      tls.myCert="/var/lib/rsyslog-relp/tls/crt"
      tls.myPrivKey="/var/lib/rsyslog-relp/tls/key"
    )

    template(name="OutFmt" type="list") {
      property(name="msg")
      constant(value="\n")
    }
    module(load="omstdout")
    action(type="omstdout" template="OutFmt")