# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: rsyslog-relp-echo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rsyslog-relp-echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: rsyslog-relp-echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if and .Values.service .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs:
    - {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: plain
      protocol: TCP
      port: 80
      targetPort: 10250
    - name: tls
      protocol: TCP
      port: 443
      targetPort: 10350