apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /helm/values/image
      value: local-skaffold/gardener-extension-shoot-rsyslog-relp
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: extension-shoot-rsyslog-relp