# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener Shoot Rsyslog Relp admission controller
name: gardener-extension-shoot-rsyslog-relp-admission
version: 0.1.0