apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener Shoot Rsyslog Relp admission controller
name: gardener-extension-shoot-rsyslog-relp
version: 0.1.0
dependencies:
  - name: application
    repository: http://localhost:10191
    version: 0.1.0
    condition: application.enabled
  - name: runtime
    repository: http://localhost:10191
    version: 0.1.0
    condition: runtime.enabled
