global:
  virtualGarden:
    enabled: false
    user:
      name: ""
  image:
    repository: eu.gcr.io/gardener-project/gardener/extensions/shoot-rsyslog-relp-admission
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      memory: "512Mi"
  metricsPort: 8080
  healthPort: 8081
  vpa:
    enabled: true
    resourcePolicy:
      minAllowed:
        cpu: 50m
        memory: 64Mi
    updatePolicy:
      updateMode: "Auto"
  webhookConfig:
    serverPort: 10250
    caBundle: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
    # Please make sure you are running `gardener@v1.42` or later before setting this to true.
    useObjectSelector: true
  # Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
  kubeconfig:
  # projectedKubeconfig:
  #   baseMountPath: /var/run/secrets/gardener.cloud
  #   genericKubeconfigSecretName: generic-token-kubeconfig
  #   tokenSecretName: access-shoot-rsyslog-relp-admission
  serviceAccountTokenVolumeProjection:
    enabled: false
    expirationSeconds: 43200
    audience: ""
  service:
    topologyAwareRouting:
      enabled: false
