# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "name" . }}
webhooks:
- name: validation.rsyslog-relp.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    {{- if .Values.virtualGarden.enabled }}
    url: {{ printf "https://%s.%s/webhooks/validate" (include "name" .) (.Release.Namespace) }}
    {{- else }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "name" . }}
      path: /webhooks/validate
    {{- end }}
    caBundle: {{ required ".Values.webhookConfig.caBundle is required" .Values.webhookConfig.caBundle | b64enc }}
