#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# TODO(plkokanov): Remove the COMPONENT_PREFIXES env var once gardener/gardener@v1.87 (contains https://github.com/gardener/gardener/pull/9008) is vendored.
COMPONENT_PREFIXES="europe-docker.pkg.dev/gardener-project/releases/gardener" \
  "$(dirname $0)"/hack/component_descriptor "$(dirname $0)"/..
