# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
images:
  alpine: image-repository:image-tag
  pause: image-repository:image-tag
  pullPolicy: IfNotPresent

podAnnotations: {}

rsyslogConfig:
  target: localhost
  port: 10515
  tls:
    enabled: false
  projectName: foo
  shootName: bar
  shootUID: 1234
  metrics:
    textfileDir: /var/lib/rsyslog-relp-configurator

auditdConfig:
  enabled: true

pspDisabled: true