# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:{{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  resourceNames:
  - gardener-extension-{{ .Values.serviceName }}
  verbs:
  - update
  - patch
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  resourceNames:
  - extension-shoot-rsyslog-relp-configuration-cleaner
  verbs:
  - get
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - shoot-rsyslog-relp-dashboards
  verbs:
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - extensions
  verbs:
  - list
  - watch
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - extensions
  - extensions/status
  resourceNames:
  - shoot-rsyslog-relp
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - scrapeconfigs
  - prometheusrules
  verbs:
  - list
  - watch
  - create
- apiGroups:
  - monitoring.coreos.com
  resources:
  - scrapeconfigs
  - prometheusrules
  resourceNames:
  - shoot-shoot-rsyslog-relp
  verbs:
  - get
  - update
  - patch
  - delete
