# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-shoot-rsyslog-relp.config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    apiVersion: rsyslog-relp.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
