# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gardener-extension-{{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ include "leaderelectionid" . }}
  - gardener-extension-heartbeat
  verbs:
  - update
  - get