# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

image:
  repository: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/shoot-rsyslog-relp-admission
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
metricsPort: 8080
healthPort: 8081
vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 50m
      memory: 64Mi
  updatePolicy:
    updateMode: "Recreate"
webhookConfig:
  serverPort: 10250
# Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
kubeconfig:
# projectedKubeconfig:
#   baseMountPath: /var/run/secrets/gardener.cloud
#   genericKubeconfigSecretName: generic-token-kubeconfig
#   tokenSecretName: access-shoot-rsyslog-relp-admission
service:
  topologyAwareRouting:
    enabled: false

gardener:
  virtualCluster:
    enabled: true
    serviceAccount: {}
#     name: gardener-extension-shoot-rsyslog-relp-admission
#     namespace: kube-system
  runtimeCluster: {}
#   priorityClassName: gardener-garden-system-400