// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by generate-imagename-constants.sh. DO NOT EDIT.

package imagevector

const (
	// ImageNameAlpine is a constant for an image in the image vector with name 'alpine'.
	ImageNameAlpine = "alpine"
	// ImageNamePauseContainer is a constant for an image in the image vector with name 'pause-container'.
	ImageNamePauseContainer = "pause-container"
)
