# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if not .Values.pspDisabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:{{ include "name" . }}
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.{{ include "name" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}