# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
images:
  alpine: image-repository:image-tag
  pause: image-repository:image-tag
  pullPolicy: IfNotPresent

certificatePath: etc/rsyslog/tls

pspDisabled: true